### ISSUE TITLE
Can't get it to work on Xcode 6.3.1

### ISSUE THREAD

**Issue by neil477** [edwardaux/XcodeExplorer#10]
I tried following the steps in the readme, but no menu item called explorer appears.

**Comment by edwardaux** [comment]
Yeah, Apple keeps releasing new versions of Xcode faster than I can add them to the compatibility list :-)  

I've just added the 6.3.1 UUID to the compatibility list... do a pull and it should work now. If not, please let me know what the `/var/log/system.log` says when you start Xcode.

**Comment by neil477** [comment]
Ha I was just finishing a pull request to add it.
