### ISSUE TITLE
XCode 6.3.2 compatibility

### ISSUE THREAD

**Issue by nicolasgoutaland** [edwardaux/XcodeExplorer#13]
Hi,
Just found a bug in XCode 6.3.2.
**[NSApp mainMenu]** return nil if called after **NSApplicationDidFinishLaunching** notification is fired.
PR #12 adresses this issue.

By the way, thanks for your very useful plugIn, helping me to work on my own ;)

Regards,

**Comment by edwardaux** [comment]
Thanks, I've merged PR #12, so can close this.
