### ISSUE TITLE
Doesn't seem to work in XCode 6.3

### ISSUE THREAD

**Issue by ExoticObjects** [edwardaux/XcodeExplorer#9]
No explorer menu appears...

**Comment by chrisbirch** [comment]
agreed

**Comment by edwardaux** [comment]
Hi guys... I merged a pull request a moment ago that should solve this. Please pull the latest code and let me know if that doesn't work.

**Comment by ExoticObjects** [comment]
It worked! Menu appears under Window -> Explorer. Thanks!
